app:
  shutdown_timeout: 5s
  log_mode: "debug" # debug, dev or prod
authorization:
  private_key_path: "secrets/chat-server.rsa"
  public_key_path: "secrets/chat-server.rsa.pub"
  token_ttl: 720h
host:
  http_port: 8082
game:
  line_game:
    levels_dir: "levels"
    rewards_conditions:
      - max_time: 10s
        reward:
          soft_currency: 100
      - max_time: 40s
        reward:
          soft_currency: 60
      - max_time: 90s
        reward:
          soft_currency: 30
  quiz:
    soft_currency_reward: 40
router:
  request_timeout: 5s
