app:
  shutdown_timeout: 5s
  log_mode: "dev" # debug, dev or prod
authorization:
  private_key_path: "secrets/chat-server.rsa"
  public_key_path: "secrets/chat-server.rsa.pub"
  token_ttl: 720h
host:
  http_port: 8081
game:
  levels_dir: "levels"
  line_game:
    check_answer: false
    rewards_conditions:
      - max_time: 10
        reward:
          soft_currency: 100
      - max_time: 40
        reward:
          soft_currency: 60
      - max_time: 90
        reward:
          soft_currency: 30
  quiz:
    soft_currency_reward: 50
  items_price:
    line_game_hint_price: 50
    line_game_stop_time_booster_price: 30
  balance:
    start_soft_currency: 100
router:
  request_timeout: 5s